before_script:
  - "npm install"
  - "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/libsodium/src/libsodium/.libs/"
  - "export LD_RUN_PATH=$LD_RUN_PATH:$(pwd)/libsodium/src/libsodium/.libs/"

stages:
  - test

checkv0_10:
  script: "make test"
  stage: test

checkv5:
  script: "make test"
  stage: test
  tags:
    - v5
